### PR TITLE
Create test_unpack_3bit_int32.py in `tests/`

### PR DESCRIPTION
**Pull request by Liberatedwinner**
Dear @mobicham,

Since the digits of binary number in `unpack_3bit_32()` are long, I think this (from L12 to L28) is alternative...
But I cannot sure whether this implement is speed-preserve.
Would you mind if checking this PR, especially in the aspect of evaluation speed?

Thank you very much.

### CODE REVIEW

**Comment by mobicham** [comment]
Thank you for your contribution @Liberatedwinner 
Would you mind explaining why this alternative is better ? From what I see, it's doing the same thing, just using a loop instead. Unrolling the loop makes it easier for torch compile to do optimizations and also makes the unpacking logic more readable.
We anyway have to unroll the loop in CUDA as well, so I am curious to hear your feedback!

**Comment by Liberatedwinner** [comment]
From my view, `0b000...` is a little long expression to type in code file and I think the loop implement is reusable to the other functions.
But by virtue of your explanation, now I realized that my view was too narrow; I had not consider of compile optimizations.
So, it is no problem to remove what I PRed.

Thank you very much.

**Comment by Liberatedwinner** [comment]
I am sorry for being late.

Then... I would like to close this PR for preventing from further confusions,
and would like to make another PR (if ok) which goes along with your idea.

Would you mind if closing this?

**Comment by mobicham** [comment]
Sure! Make sure to add unit tests on multiple large tensor shapes to make sure it works fine with the hex format

**Pull request closed without merging**
