### PR TITLE
directly loading weights in specified device

### PR DESCRIPTION
**Pull request by viraatdas**
Implemented dynamic map_location to ensure that model weights are loaded on the appropriate specified device.

## Problem:
We see that even though "cpu" is the device provided, we are running into CUDA memory issue. 

```
model_id = 'mobiuslabsgmbh/Mixtral-8x7B-Instruct-v0.1-hf-4bit_g64-HQQ'

#Load the model
from hqq.engine.hf import HQQModelForCausalLM, AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained(model_id)
model     = HQQModelForCausalLM.from_quantized(model_id, device="cpu")
```

Output

```
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/Reduce2Bit-O_KBCo5u/lib/python3.10/site-packages/hqq/models/base.py", line 328, in from_quantized
    weights = cls.load_weights(save_dir)
  File "/home/ubuntu/.local/share/virtualenvs/Reduce2Bit-O_KBCo5u/lib/python3.10/site-packages/hqq/models/base.py", line 195, in load_weights
    return torch.load(cls.get_weight_file(save_dir), map_location=map_location)
  File "/home/ubuntu/.local/share/virtualenvs/Reduce2Bit-O_KBCo5u/lib/python3.10/site-packages/torch/serialization.py", line 1026, in load
    return _load(opened_zipfile,
  File "/home/ubuntu/.local/share/virtualenvs/Reduce2Bit-O_KBCo5u/lib/python3.10/site-packages/torch/serialization.py", line 1438, in _load
    result = unpickler.load()
  File "/home/ubuntu/.local/share/virtualenvs/Reduce2Bit-O_KBCo5u/lib/python3.10/site-packages/torch/serialization.py", line 1408, in persistent_load
    typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/home/ubuntu/.local/share/virtualenvs/Reduce2Bit-O_KBCo5u/lib/python3.10/site-packages/torch/serialization.py", line 1382, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "/home/ubuntu/.local/share/virtualenvs/Reduce2Bit-O_KBCo5u/lib/python3.10/site-packages/torch/serialization.py", line 391, in default_restore_location
    result = fn(storage, location)
  File "/home/ubuntu/.local/share/virtualenvs/Reduce2Bit-O_KBCo5u/lib/python3.10/site-packages/torch/serialization.py", line 271, in _cuda_deserialize
    return obj.cuda(device)
  File "/home/ubuntu/.local/share/virtualenvs/Reduce2Bit-O_KBCo5u/lib/python3.10/site-packages/torch/_utils.py", line 115, in _cuda
    untyped_storage = torch.UntypedStorage(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 28.00 MiB. GPU 0 has a total capacity of 15.77 GiB of which 27.38 MiB is free. Including non-PyTorch memory, this process has 15.74 GiB memory in use. Of the allocated memory 15.44 GiB is allocated by PyTorch, and 4.31 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```
## Why?
This was happening because whenever we were loading weights, it was trying to load it into the available CUDA device. This device ensures that the correct map location is used.

### CODE REVIEW

**Comment by mobicham** [comment]
Hi, thanks for spotting that! Can you please just remove the type all together?
`def load_weights(cls, save_dir: str, map_location=None)`
By the way, CPU runtime is not supported and forcing `device='cpu' `will have an unexpected behavior.

**Comment by viraatdas** [comment]
Makes sense - will do.

**Comment by viraatdas** [comment]
I have updated the load_weights method by removing the map_location parameter. 

This modification should not impact any current users of the method, as the parameter was not actively utilized within the function. However, if any users have been including the map_location argument in their function calls, they will need to remove it. This should be a straightforward adjustment.

Thanks!

**Comment by mobicham** [comment]
Hey, 
you can just keep it and do `def load_weights(cls, save_dir: str, map_location=None)` instead, so people who have used map_location for some reason don't run into issues. Also, it would allow more efficient loading on different gpus.

**Comment by viraatdas** [comment]
In that case, shouldn't `map_location` be passed into torch.load(..)?

```
    @classmethod
    def load_weights(cls, save_dir: str, map_location=None):
        print("CPU runtime is not supported. Will attempt to load the weights in the GPU.")
        return torch.load(cls.get_weight_file(save_dir), map_location=map_location)
```

**Comment by mobicham** [comment]
It is passed to torch.load:
original code
```Python
    @classmethod
    def load_weights(cls, save_dir: str, map_location: bool = None):
        return torch.load(cls.get_weight_file(save_dir), map_location=map_location)
```

New
```Python
    @classmethod
    def load_weights(cls, save_dir: str, map_location = None):
        return torch.load(cls.get_weight_file(save_dir), map_location=map_location)
```

**Comment by viraatdas** [comment]
I see what you are saying - added that minor change. Thanks for the patient explanation.

**Comment by mobicham** [comment]
Sorry for the delay @viraatdas

**Comment by viraatdas** [comment]
np - thanks

**Pull request merged**
